### PR TITLE
Update sap_checklist.en.json

### PR DESCRIPTION
**Pull request by NaokiIgarashi**
I modified to description about Application Gateway and SAP Web Dispatcher.

### CODE REVIEW

**Comment by erjosito** [comment]
@NaokiIgarashi there seem to be conflicts in this PR...

**Comment by NaokiIgarashi** [comment]
I renewed a guid.

**Comment by erjosito** [comment]
Fair enough, but until the conflicts are not solved, it is not possible to merge...

**Comment by NaokiIgarashi** [comment]
Hi Jose, 
I resolved my conflicts...
Please check it!

**Comment by erjosito** [comment]
One of the preflight checks failed. I believe you are missing a comma in the JSON?

**Comment by NaokiIgarashi** [comment]
I'm so sorry!
I repaired it!

**Review by erjosito — APPROVED** [review]

**Pull request merged**
