### PR TITLE
Naigaras sap checklist

### PR DESCRIPTION
**Pull request by NaokiIgarashi**
I updated about **"Security, Governance and Compliance"**
Please review my modifications.

### CODE REVIEW

**Review by AlastairMorrison — COMMENTED** [review]
In reference to the text for "LOCK" resources, this could maybe be adjusted to suggest that resource polices are included to enforce this.

**Review by AlastairMorrison — CHANGES_REQUESTED** [review]
Suggest that text comment is reviewed for Microsoft Defender to advise exclusion of directories on database servers rather than full server.
Add link to Cameron Gardiner's blog for MDE.  https://techcommunity.microsoft.com/t5/running-sap-applications-on-the/microsoft-defender-endpoint-mde-for-sap-applications-on-windows/ba-p/3912268

New documentation is about to be published for MDE for SAP which can be added to checklist later.

**Review by AlastairMorrison — CHANGES_REQUESTED** [review]
Suggestion that text for "SAP database server encryption" is updated regarding Azure SQL Database.  Azure SQL database is only supported for Business Objects and not native SAP systems.  Text implies it is supported for regular SAP data and log files.

**Review by AlastairMorrison — CHANGES_REQUESTED** [review]
Suggest that text is altered where "with Azure, you can use antimalware software from security vendors..." only references Microsoft and not third-party specific vendors.

**Comment by NaokiIgarashi** [comment]
Hi @AlastairMorrison,
Thank you for your valuable comments. I have corrected my content you pointed out, so please check again.

**Comment by erjosito** [comment]
@AlastairMorrison @mottach It would be great if you could review (and eventually approve) @NaokiIgarashi 's changes

**Review by AlastairMorrison — APPROVED** [review]

**Pull request merged**
