### PR TITLE
Adding some identity best practices

### PR DESCRIPTION
**Pull request by chboudry**

### CODE REVIEW

**Comment by erjosito** [comment]
Thanks @chboudry !! One small ask, until Mark verifies this: would it be possible removing the localization in the More Info links (`en-us`)? Thanks!

**Comment by erjosito** [comment]
Added @MGodfrey50 as reviewer

**Comment by erjosito** [comment]
@MGodfrey50 any chance to review this?

**Comment by MGodfrey50** [comment]
Thanks for the nudge - will do it today.

MG


Sent from Outlook<http://aka.ms/weboutlook>

**Review by MGodfrey50 — APPROVED** [review]
Excellent Charles!

**Review by MGodfrey50 — COMMENTED** [review]
Good feedback on removing localization.

**Pull request merged**
