### PR TITLE
Creation of some additional checks

### PR DESCRIPTION
**Pull request by fskelly**
Added more Resource Graph queries for ESLZ

### CODE REVIEW

**Review by erjosito — CHANGES_REQUESTED** [review]
Thanks @fskelly ! Could you please remove the double quotes from the queries and replace them with single quotes? Otherwise JSON gets crazy :-)  (I am actually surprised that this passed the JSON linting test)

**Comment by erjosito** [comment]
@fskelly another question: are you intending to merge a change to the Excel spreadsheet? If not, I would kindly ask to remove the changes to the spreadsheet from this PR.

**Comment by fskelly** [comment]
@erjosito Hope that is correct now - thank you for picking those issues up 👍

**Comment by erjosito** [comment]
Thanks @fskelly ! I still see the Excel spreadsheet is part of this PR. Are you intending to change the spreadsheet too?
- If yes: which changes are included? We recently changes some formatting, so your version of the spreadsheet is probably old
- If not: could you please remove it from the PR?

**Pull request closed without merging**
