### PR TITLE
grpah queries added

### PR DESCRIPTION
**Pull request by BevanSin**

### CODE REVIEW

**Comment by BevanSin** [comment]
Added queries to "Secure transfer to storage accounts should be enabled" and "Enable container soft delete for the storage account to recover a deleted container and its contents.",

**Comment by BevanSin** [comment]
Actually we can cancel the storage one - looks like the graph api doesnt support Features of storage accounts so it was returning a false result for the soft delete query

As for the supportsHttpsTrafficOnly query - I cant get it to work with extend - it fails for me @erjosito 

`az graph query -q "Resources | where type =~ 'Microsoft.Storage/storageAccounts' | extend compliant=(properties.supportsHttpsTrafficOnly == true, 1, 0) | project id, compliant"`

But this works:
`az graph query -q "Resources | where type =~ 'Microsoft.Storage/storageAccounts' | extend compliant=iif(properties.supportsHttpsTrafficOnly == true, 1, 0) | project id, compliant"
`

**Comment by erjosito** [comment]
Ah, my bad, I was too quick typing... What about this?

```bash
query="Resources | where type =~ 'Microsoft.Storage/storageAccounts' | extend compliant=(properties.supportsHttpsTrafficOnly == true) | project id, compliant"
az graph query -q "$query" --query data -o table
```

**Comment by erjosito** [comment]
Closing since no activity

**Pull request closed without merging**
