### PR TITLE
Add JSON schema for checklist files

### PR DESCRIPTION
**Pull request by jelledruyts**
Helps in documenting the expected properties and real-time validation.

### CODE REVIEW

**Comment by jelledruyts** [comment]
In the `checklist.schema.json` I've tried to summarize the description of the properties, but I'm not sure about the difference between `graph`, `graph_success` and `graph_failure`. I also left the description for `cost`, `ha`, `scale`, `security` and `simple` properties empty as I didn't see what they were actually used for - would be good if someone could update where possible :-)

**Comment by erjosito** [comment]
Hey @jelledruyts thanks for this! The graph_success and graph_failure fields are legacy, in the next version we will consolidate to a single field (graph), to simplify graph contributions.

**Comment by erjosito** [comment]
Regarding the cost/ha/scale/security/simple fields, this is a pilot to document the areas where a certain recommendation has effect on, but so far they only exist in the AKS one, and feedback on it hasnt been spectacular. Not sure if this is relevant at all to your question, hth.

**Comment by jelledruyts** [comment]
@erjosito thanks for clarifying, have updated the descriptions to call this out. Note: I've checked to be sure and adding the $schema to the checklists didn't break the Excel VBA stuff ;-)

**Review by erjosito — APPROVED** [review]

**Pull request merged**
