### PR TITLE
updates to ID column

### PR DESCRIPTION
**Pull request by igorjnzl**
Updating ID column to reflect an order that improves flow of checklist

### CODE REVIEW

**Comment by brsteph** [comment]
@BeckyHope19  - Can you review this and approve?

**Comment by igorjnzl** [comment]
@hgotar1 are you able to take a look pls?

**Comment by brsteph** [comment]
@brsteph - for internal tracking

**Review by mbilalamjad — APPROVED** [review]
LGTM

**Review by brsteph — APPROVED** [review]

**Pull request merged**
