### PR TITLE
Update avd_checklist.en.json

### PR DESCRIPTION
**Pull request by BeatrizSilv**
Suggesting the addition of a recommendation to consider Azure AD App Proxy as a potential alternative to AVD, if users only need access to internal apps.

### CODE REVIEW

**Comment by igorpag** [comment]
Hi @BeatrizSilv, I have to kindly disagree here. It is not nice, in context of one service to recommend dropping it and use another service. This could be perceived negatively from both PG and the customer. Additionally, there are several cases where this recommendation cannot apply. Just to mention few of them: 

- Support for large number of users: as we know, AVD can support 1000s or dozens of 1000s of users and multiple applications, while Azure AD App Proxy cannot scale at that level. 
- The internal application/s are not web based. 
- You need to leverage additional services like OneDrive and Teams.
- You need to have a user profile. 

Happy to discuss in a call... change my mind :-)

**Comment by erjosito** [comment]
Mmmh, not sure I agree @igorpag . It is not about being nice or not, but about making sure that customers select the right Azure service. Sure you will find cases where the recommendation doesnt apply, it is just considering it in case it helps, and if it doesnt, then throw it away. We have had situations where customers were not aware of AAD App Proxy and started expensive AVD projects, which later could be reduced for a subset of the users that only needed web access to internal apps.

**Comment by igorpag** [comment]
@erjosito we all agree on the concept, that is ensuring customers select the right Azure service, but IMO this "check" should not be done in the service specific checklist, instead should be done before arriving at the checklist step. Once you enter the checklist, that aspect should be sorted out.

**Comment by BeatrizSilv** [comment]
Would the LZ review checklist be a better place to add this recommendation to?

**Comment by igorpag** [comment]
@BeatrizSilv really like your idea to include in the LZ checklist, makes sense to me, but please don't limit yourself to my feedback only.

**Comment by BeatrizSilv** [comment]
@igorpag I submitted a new PR for the LZ checklist. Can you close this one? Thanks!

**Pull request closed without merging**
