### PR TITLE
Update alz_checklist.en.json

### PR DESCRIPTION
**Pull request by hgotar1**
This pull request is related to the GitHub issue https://github.com/Azure/review-checklists/issues/743. In fact there is a reference to DDOS
enforcement for public IP on 2 entries in the checklist (D01.03 and D06.06). I am suggesting the removal of the D01.03 because it is only related to application landing
zones. The D06.06 cover all Virtual networks with public IP and its link is pointing to the reference architecture.  The removal of D01.03 is not impacting the numbering 
of other entries. The next entry after fetching the check list is D02.01.

### CODE REVIEW

**Review by brsteph — APPROVED** [review]
Good catch!

**Review by igorjnzl — APPROVED** [review]
LGTM

**Comment by igorjnzl** [comment]
@hgotar1 can you look into the merge conflict pls

**Comment by hgotar1** [comment]
The JSON tag for D01.03 seems to be gone after sync (fetch) another pull request may have successfully remove it already

**Pull request closed without merging**
