### PR TITLE
Updates to support multi region guidance

### PR DESCRIPTION
**Pull request by igorjnzl**
## Description
Additional guidance to support ALZ multi region updates

## Checklist

- [x] I've tested my changes to ensure they are ready for review.
- [x] I've read the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) guide.
- [ ] I've updated the documentation (if applicable).
- [ ] Resource Graph queries have been included (and tested) for recommendations where ever possible[^note].
- [ ] Resource Graph queries have NOT been included (please explain below).

[^note]:
    Details on how to add Azure Resource Graph queries to recommendations can be found [here](../blob/main/CONTRIBUTING.md#1-adding-or-modifying-resource-graph-queries).

### CODE REVIEW

**Comment by igorjnzl** [comment]
@brsteph what are your thoughts on additional maybe removing C03.02?

**Comment by brsteph** [comment]
> @brsteph what are your thoughts on additional maybe removing C03.02?

The idea being that since we have recommendations for identity, network, and logging, we don't need the over all?

I think I am OK with it, just to try to keep the list from growing.

**Comment by brsteph** [comment]
I'll wait until we get that change in to approve!

**Comment by jodyford-msft** [comment]
please add line item id and checklist filename to PR title

**Review by hgotar1 — APPROVED** [review]
First I thought they were no ID on line 657 then I saw you adding that with following updates on your commit.
Everything seems ok - Thanks

**Review by brsteph — APPROVED** [review]

**Pull request merged**
