### PR TITLE
ADD template checklist file and related contributing instructions

### PR DESCRIPTION
**Pull request by jomacedo**
@erjosito the file won't appear in the UI as it's missing the .<language>. in the name

### CODE REVIEW

**Comment by erjosito** [comment]
Hey @jomacedo could you please add the `service` field to the sample item? Thanks!

**Comment by jomacedo** [comment]
> Hey @jomacedo could you please add the `service` field to the sample item? Thanks!

Added!

**Comment by erjosito** [comment]
Oh, sorry for being a pain, I just noticed that the "yes/no" section is missing too. This is mostly for storing the value of yes/no options in different languages, required by the schema:

```
    "yesno": [
        {
            "name": "Yes"
        },
        {
            "name": "No"
        }
    ],
```

Thanks for your patience!

**Comment by jomacedo** [comment]
Aha!

I thought this wasn't used! I'll add it in a jiffy!


Best Regards,

João Carlos Santos  |  Customer Engineer  | Azure FastTrack AppDev  | EMAIL ***@***.******@***.***>  | PHONE +351 968 764 609

Learn more about FastTrack for Azure, here<https://azure.microsoft.com/en-us/programs/azure-fasttrack/>.



***@***.***?anonymous&ep=signature>            Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________

**Comment by jomacedo** [comment]
Done!

**Review by erjosito — APPROVED** [review]

**Pull request merged**
