### PR TITLE
Added/edited content based on feedbacks from CxE Network Security team 

### PR DESCRIPTION
**Pull request by igorpag**

### CODE REVIEW

**Review by erjosito — APPROVED** [review]

**Comment by erjosito** [comment]
＠Microsoft/alz-checklist-contributors, when you approve we are ready to merge this :-)

**Comment by brsteph** [comment]
Adding fta-alz-vteam to reviewers

**Review by brsteph — APPROVED** [review]

**Review by andredewes — APPROVED** [review]

**Comment by erjosito** [comment]
> Adding fta-alz-vteam to reviewers
> 
> Edit: Missed that Jose had approved for that team and that removed the team record!

Thanks @brsteph !

**Review by jtracey93 — APPROVED** [review]
LGTM

**Pull request merged**
