### PR TITLE
ALZ - Remove duplicate

### PR DESCRIPTION
**Pull request by hgotar1**
There appears to be a duplicate checklist ID D06.06 and D01.03. Both essentially ask the same question.

D01.03: "Use a DDoS Network or IP protection plans for all Public IP addresses in application landing zones."
D06.06: "Use Azure DDoS Network or IP Protection plans to help protect Public IP Addresses endpoints within the virtual networks."
Removing D01.03

### CODE REVIEW

**Comment by brsteph** [comment]
We have another draft PR were we were cutting D6.06 and keeping D1.03 - would that be OK?

**Comment by hgotar1** [comment]
> We have another draft PR were we were cutting D6.06 and keeping D1.03 - would that be OK?

Yes that will be ok --- Please update this PR once the draft has been processed

**Comment by brsteph** [comment]
@hgotar1  - This has been updated in main.  Can you confirm that main now reflects what is needed?

If things look good, or there is no response by Friday, I'll close this - but we can always reopen it to address later!

**Comment by hgotar1** [comment]
I am closing this pull request since the concern has been address by another PR -  As per previous comments.

**Comment by hgotar1** [comment]
Closing as this is handle by another PR

**Pull request closed without merging**
