### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codebytes**
This pull request includes significant updates to the documentation and scripts for Azure Review Checklists, focusing on improving usability and organization. The most important changes include restructuring the `README.md` file, moving detailed instructions to specific sub-files, and updating deployment scripts.

Documentation improvements:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5-R22): Added a detailed introduction and reorganized content to improve clarity. The sections on Azure design reviews and repository purpose were removed to streamline the document. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5-R22) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L34-L113)
* [`spreadsheet/README.md`](diffhunk://#diff-0a594538129a7cf9def357cb97965da05e3c16494c11d94c138e81e30180cfc4R1-R54): Moved detailed instructions on using the Excel spreadsheet for Azure reviews, including security settings for running macros and generating JSON checklist files.

### CODE REVIEW

**Comment by codebytes** [comment]
@brsteph

**Comment by erjosito** [comment]
Thanks a lot @codebytes ! The picture links in spreadsheet/README.md seem to be broken, probably `./pictures/...` needs to be replaced with `../pictures/...`? I like the changes. @sdolgin , @brsteph What do you think?

**Comment by erjosito** [comment]
We can take this chance to update the docs with reference to the macrofree sheets or to the external recos (APRL, service guides, etc), but we can leave that out-of-scope of this PR.

**Review by sdolgin — APPROVED** [review]
images look good now!

**Comment by sdolgin** [comment]
> Thanks a lot @codebytes ! The picture links in spreadsheet/README.md seem to be broken, probably `./pictures/...` needs to be replaced with `../pictures/...`? I like the changes. @sdolgin , @brsteph What do you think?

images are working now. Thanks @codebytes! @erjosito unless you have anything to address this is ready to merge.

**Comment by brsteph** [comment]
I like it and would love to see it in.  I think we can make the changes and collect feedback if there is an ask to adjust back in someway.

**Review by erjosito — APPROVED** [review]

**Comment by erjosito** [comment]
Merged! THANKS @codebytes!

**Pull request merged**
