### PR TITLE
Addition of ARG queries and rewording

### PR DESCRIPTION
**Pull request by fskelly**
Add queries to ALZ Checklist.
Reworded SIG to ACG in AVD checklist

### CODE REVIEW

**Review by igorpag — APPROVED** [review]

**Comment by igorpag** [comment]
@erjosito which crazy config here requires 9 reviewers!

**Comment by fskelly** [comment]
IT seems to be the default - yikes!!!!!! Sorry - and it is a really simple change!!!
IF I can change reviewer list - happy to close and select those reviewers, everyone's time is valuable...

**Comment by igorpag** [comment]
Tried myself but I can't. @erjosito is it possible to change this configuration/requirement? thanks.

**Review by sdolgin — APPROVED** [review]
lz_checklist reviewed... new ARG queries look good.

**Pull request merged**
