### PR TITLE
Update for avs_checklist.en.json

### PR DESCRIPTION
**Pull request by aarhoden**
Update for avs_checklist.en.json

### CODE REVIEW

**Comment by erjosito** [comment]
Hey @robinher, courtesy of @MGodfrey50 and @aarhoden ! This is a significant change, unfortunately the changes are not tracked correctly

**Comment by aarhoden** [comment]
> 
I agree to the license/cla.

**Comment by aarhoden** [comment]
Hello @robinher and @MGodfrey50. Should we schedule a review session? Best, @aarhoden

**Review by MGodfrey50 — APPROVED** [review]
Reviewed

**Comment by aarhoden** [comment]
Also validated through the current Preview Excel workbook successfully.

**Comment by erjosito** [comment]
We made it! :-)

**Pull request merged**
