### PR TITLE
Update alz_checklist.en.json (Governance Training Links)

### PR DESCRIPTION
**Pull request by alisakina99**

### CODE REVIEW

**Comment by brsteph** [comment]
@BeckyHope19 - Would you be able to review this one?

**Review by igorjnzl — APPROVED** [review]

**Comment by igorjnzl** [comment]
Hi @Azure/fta-alz-vteam do you mind reviewing pls ?

**Review by brsteph — APPROVED** [review]

**Comment by igorjnzl** [comment]
@brsteph what's the linting check complaining about on this run?

**Comment by erjosito** [comment]
Funny, I can't see any JSON error either...

**Comment by erjosito** [comment]
Ah, got it, it is a missing comma in line 134. It possibly went through in a previous PR without anybody noticing?

**Comment by igorjnzl** [comment]
@alisakina99 are you able to make the quick fix on this one?

**Review by brsteph — APPROVED** [review]
Training adds look good!

**Pull request merged**
