### PR TITLE
Adding NSG related item to alz

### PR DESCRIPTION
**Pull request by yamorish**
Adding NSG related item to alz.

I confirmed NSG rule limit of 1000 is the sum of inbound and outbound rules. Also, default NSG rules are not considered in calculation.

### CODE REVIEW

**Comment by JefferyMitchell** [comment]
@erjosito @yamorish I think this may not age well and we will end up having to update continually the latest rule limit. Can we say to review the limit and quota with a link and plan for that. Like "Consider the limit of NSG rules" for example. I think this will last longer and require fewer updates.

**Comment by brsteph** [comment]
I am good with this with Jeff's notes above - once we make that change we can merge it in.

**Comment by igorjnzl** [comment]
Is it possible to make this check a bit more generic? Possibly link to our docs around limits for particular services? We already have a check for subscription quotas. 

Interesting to hear if this is a common theme (NSG rule limit) in previous reviews?

**Comment by yamorish** [comment]
@igorjnzl,  there are few existing items that warn limit for specific service. Such as,

- Consider the limit of routes per route table (400).
- When connecting spoke virtual networks to the central hub virtual network, consider VNet peering limits (500), the maximum number of prefixes that can be advertised via ExpressRoute (1000)

I created this PR which will be consistent with these existing items. I agree with you that we already have a generic check for subscription quotas and all quota check shouldn't be included in this checklist. But I think NSG rule of 1000 is common compared to other limits and is worth including in the checklist to warn customers before they hit the (hard) limit. 

I'm fine waiting until it's aged well.

**Comment by erjosito** [comment]
While I see that putting limits in the actual recommendations and ARG queries increases the maintenance effort, IMHO it increases as well the added value for the customer. Saying "go and figure out the limit in Azure docs and see if you are good" is not quite the same as saying "Hey you are at 80% of limit X". I would frankly go for using the actual number in the rule, as long as it is a number that doesn't change too often (such as the 400 route limit or the 1K NSG rule limit).

Thoughts @brsteph @sdolgin ?

**Review by erjosito — APPROVED** [review]

**Comment by erjosito** [comment]
Merging!

**Comment by brsteph** [comment]
Sorry I have been behind on these items - I kind of see it on both sides.  I think we might get more feedback as it gets used and see.

I am thinking that it may be beneficial to have the rule be more general still, such as "make sure you are aware of subscription limits."  We should probably have some standard as to when and where we give this specific of a recommendation - this might be better on a Networking checklist, for example.

**Pull request merged**
