### PR TITLE
Adding WAF pillar to AVD checklist

### PR DESCRIPTION
**Pull request by bagwyth**
Adding WAF pillar categorisation to AVD checklist content.

### CODE REVIEW

**Comment by erjosito** [comment]
@igorpag and @mikewarr if it is OK with you I will merge this?

**Comment by igorpag** [comment]
Hi @erjosito, need to check a thing by EOD, will update you once done. OK?

**Review by igorpag — APPROVED** [review]

**Comment by igorpag** [comment]
#sign-off

**Comment by igorpag** [comment]
@erjosito approved and merged. Thank you.

**Pull request merged**
